language: go

go:
  - 1.9.x
  - master

sudo: false

before_install:
  - curl https://glide.sh/get | sh

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - glide install

script:
  - go test ./...
  - go build .
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  - pwd
  - ls


notifications:
  email:
    recipients:
      - inputx@gmail.com
    on_success: change # default: change
    on_failure: always # default: always