language: go

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - tip

sudo: false

before_install:
  - curl https://glide.sh/get | sh
  - glide install
  
script:
  - go build .


notifications:
  email:
    recipients:
      - inputx@gmail.com
    on_success: change # default: change
    on_failure: always # default: always