language: go

go:
  - 1.9.x
  - master

sudo: false

before_install:
  - curl https://glide.sh/get | sh
  - glide install
  
script:
  - go test ./...
  - go build .
  - pwd
  - ls


notifications:
  email:
    recipients:
      - inputx@gmail.com
    on_success: change # default: change
    on_failure: always # default: always