language: go

go:
  - 1.9.x

sudo: false

before_install:
  - curl https://glide.sh/get | sh
  - go get github.com/modocache/gover
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

install:

  - glide install

script:
  - ls
  - go test -covermode=count -coverprofile=coverage-container.coverprofile  ./container/
  - go test -covermode=count -coverprofile=coverage-subsystems.coverprofile  ./cgroups/subsystems
  - $HOME/gopath/bin/gover
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN
  - go build .
  - pwd
  - ls


notifications:
  email:
    recipients:
      - inputx@gmail.com
    on_success: change # default: change
    on_failure: always # default: always